#  MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html


staging::
  adapter: sqlserver
  mode: odbc
  dsn: 192.168.0.130
  username: testsql
  password: testsql
  host: UMPC

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: finance_test
  pool: 5
  username: root
  password: "*sys64738"
  socket: /var/run/mysqld/mysqld.sock


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: finance_test
  pool: 5
  username: root
  password: "*hapoalim2005"
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: sqlserver
  mode: dblib
  dataserver: 192.168.0.130
  database: Singapore_Reporting
  username: testsql
  password: testsql
  timeout: 5000

cucumber:
  <<: *test
